! Input file for program Qdyn

&general
  run=1,                       ! Type of job (0 - real time propagation, 1 - imaginary time propagation)
  nstep=200,                  ! Number of steps
  dt=0.5,                      ! Timestep [a.u.]
  dtwrite=10.0,                ! Printing every time unit (modulo)

  ngrid=512,                   ! Number of grid points (power of 2 for FFT)
  xmin=-37.0,                  ! Grid xmin, xmax same for all dimensions
  xmax=37.0,
  mass=1.0,                    ! Reduced mass of system [a.u.]
  wf=0,                        ! Initial wavefunction (0 - generated by program, 1 - wf.chk file)
  nstates=10

  rank=1,                      ! Dimensionality
  pot='0.005*(x)**2'  ! Potential

/

