name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  intel_build:
    name: Intel OneAPI build
    runs-on: ubuntu-20.04
    env:
      FC: mpiifort
      APT_PACKAGES: >-
        intel-oneapi-compiler-fortran
        intel-oneapi-mpi
        intel-oneapi-mpi-devel

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Install fftw
      run: |
        ls
        ls ${{ github.workspace }}
#       tar -xf fftw/fftw.tar.gz
#       cd fftw/fftw
#       bash compile.sh

#   - name: Add Intel repository
#     run: |
#       wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
#       sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
#       rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
#       echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
#       sudo apt-get update

#   - name: Install Intel oneAPI compiler
#     run: |
#       sudo apt-get install ${{ env.APT_PACKAGES }}
#       source /opt/intel/oneapi/setvars.sh
#       printenv >> $GITHUB_ENV

#   - name: Build ABIN
#     run: cd src/; make clean && make
